from numpy import dot
from utils import BOD_Calculation, Entropy_Calculation, PCA_Calculation

def equal_weights(data):
    """
    Calculates composite indicator given equal weights for each column in the data.
    This function returns a Series where each value is an evaluation of the composite indicator generated by the method equal weight.
    Parameters:
    data : DataFrame
        A pandas DataFrame containing the data for which equal weights are to be calculated.
    Returns: Series
        A pandas Series where each value is the scora of an object in data.
    """
    return data.apply(lambda x: dot(x, [1/len(data.columns) for _ in data.columns]), axis=1)

def specialist_weights(data, weights):
    """
    Calculates composite indicator given specialist weights for each column in the data.
    This function returns a Series where each value is an evaluation of the composite indicator generated by the method specialist weights.
    Parameters:
    data : DataFrame
        A pandas DataFrame containing the data for which specialist weights are to be calculated.
    weights : list
        A list of weights corresponding to each column in the data.
    Returns: Series
        A pandas Series where each value is the score of an object in data based on the provided weights.
    """
    return data.apply(lambda x: dot(x, [weight/sum(weights) for weight in weights]), axis=1)

def BoD_indicator(data):
    """
    Calculates the BoD (Balance of Distribution) indicator for the given data.
    This function returns a Series where each value is the BoD score for an object in the data.
    Parameters:
    data : DataFrame
        A pandas DataFrame containing the data for which the BoD indicator is to be calculated.
    Returns: Series
        A pandas Series where each value is the BoD score of an object in data.
    """
    return Series([r.ci for r in BOD_Calculation(data).run()])
    
def Entropy_indicator(data):
    """
    Calculates the Entropy indicator for the given data.
    This function returns a Series where each value is the Entropy score for an object in the data.
    Parameters:
    data : DataFrame
        A pandas DataFrame containing the data for which the Entropy indicator is to be calculated.
    Returns: Series
        A pandas Series where each value is the Entropy score of an object in data.
    """
    return Series([r.ci for r in Entropy_Calculation(data).run()])
    
def PCA_indicator(data):
    """
    Calculates the PCA (Principal Component Analysis) indicator for the given data.
    This function returns a Series where each value is the PCA score for an object in the data.
    Parameters:
    data : DataFrame
        A pandas DataFrame containing the data for which the PCA indicator is to be calculated.
    Returns: Series
        A pandas Series where each value is the PCA score of an object in data.
    """
    return Series([r.ci for r in PCA_Calculation(data).run()])